#  API environment variables
apiBaseUrl=https://automationexercise.com
createAccountEndpoint=/api/createAccount
successStatusCode=200
badRequestStatusCode=400
createdStatusCode=201
loginWithoutEmailMessage=Bad request, email or password parameter is missing in POST request.
userExistMessage=User exists!
userCreatedMessage=User created!
loginEndpoint=/api/verifyLogin
searchProductEndpoint=/api/searchProduct
searchItem=tshirt

# UI environment variables
baseUrl=https://automationexercise.com
browser=chrome
timeout=10