#  Base API URL
apiBaseUrl=https://automationexercise.com
#------------------------------------ Status codes---------------------------------------------------
successStatusCode=200
badRequestStatusCode=400
notFoundStatusCode=404
createdStatusCode=201
methodNotSupportedStatusCode=405
#------------------------------------- API Response messages------------------------------------------- 
loginWithoutEmailMessage=Bad request, email or password parameter is missing in POST request.
userExistMessage=User exists!
userCreatedMessage=User created!
userUpdatedMessage=User updated!
userDeletedMessage=Account deleted!
deleteNonExistingUserMessage=User not found!
methodNotSupportedMessage=This request method is not supported.
#------------------------------------API Endpoint------------------------------------------------------ 
createAccountEndpoint=/api/createAccount
loginEndpoint=/api/verifyLogin
searchProductEndpoint=/api/searchProduct
getUserDetailsByEmailEndpoint=/api/getUserDetailByEmail
updateUserAccountEndpoint=/api/updateAccount
deleteUserAccountEndpoint=/api/deleteAccount
#------------------------------------User data---------------------------------------------------------
searchItem=tshirt
updatedNameText=Ayanda Khaka
updatedAddress1Text=4888 Tswelopele ext8 Thembisa
updatedMobileNumber=0634943658
invalidEmail=ayaskhaka@gmail.com	
invalidPassword=password1234

# -----------------------------------UI environment variables-----------------------------------------
baseUrl=https://automationexercise.com
browser=chrome
timeout=10