#Allure Test Environment Information
#Fri Aug 07 14:44:25 SAST 2026
OS\ Version=10.0
Execution\ Mode=local
Java\ Version=17.0.12
Test\ Environment=QA
Operating\ System=Windows 11
Browser\ Version=150.0.4078.105
Browser=MicrosoftEdge
