#Allure Test Environment Information
#Wed Jul 22 14:01:51 SAST 2026
Browser=MicrosoftEdge
Browser\ Version=150.0.4078.65
Execution\ Mode=local
Java\ Version=21.0.8
OS\ Version=10.0
Operating\ System=Windows 11
Test\ Environment=QA
