name: API Automation CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      # Setup GitHub Pages
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      # Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Verify Java and Maven
      - name: Verify Java and Maven
        run: |
          java -version
          mvn -version

      # Run API Tests
      - name: Run API Tests
        run: |
          mvn clean test -DsuiteXmlFile=src/test/resources/testng-api.xml

      # Generate Allure Report
      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      # Customize Allure Report title
      - name: Customize Allure Report
        if: always()
        run: |
          find target/site/allure-maven-plugin -type f -name "*.js" -exec sed -i 's/Allure Report/Hybrid UI \& API Test Automation — QA Report/g' {} +

      # Upload GitHub Pages Artifact
      - name: Upload GitHub Pages Artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/site/allure-maven-plugin/

      # Upload Surefire Reports
      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      # Upload Allure Results
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results/

      # Upload Allure HTML Report
      - name: Upload Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: api-tests
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4