name: API Automation CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      # 1. Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Set up Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3. Verify Java and Maven
      - name: Verify Java and Maven
        run: |
          java -version
          mvn -version

      # 4. Run API Tests
      - name: Run API Tests
        run: |
          mvn clean test \
          -DsuiteXmlFile=src/test/resources/testng-api.xml

      # 5. Generate Allure Report
      - name: Generate Allure Report
        if: always()
        run: mvn allure:report
        
      # 6. Upload report for GitHub Pages
      - name: Upload GitHub Pages Artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/site/allure-maven-plugin/

      # 7. Upload Surefire Reports
      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      # 8. Upload Allure Results
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results/

      # 7. Upload Allure HTML Report
      - name: Upload Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/